<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="SystemEntryForm.aspx.cs" Inherits="SystemEntryForm" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <link href="Style/desktop.css" rel="stylesheet" />
    <script src="Scripts/Sidebar.js"></script>
    <div id ="sidebar">
        <div class="toggle-btn" onclick="toggleSidebar();">
            <span></span>
            <span></span>
            <span></span>
        </div>
        <ul>
            <li> <asp:Label ID="lblUser" runat="server" Text=""></asp:Label></li>
            <li> <a href ="/UserOptions.aspx">User Options</a></li>
            <li> <a href="/ViewRewards.aspx">View Rewards</a></li>
            <li> <a href ="/AddRewardProviders.aspx">View Reward Providers</a></li>
            <li>Add Community Events</li>
            <li><a href="LoginPage.aspx"></a></li>
        </ul>
    </div>
                <p style="width: 643px">
                &nbsp;&nbsp;&nbsp;&nbsp;Search Users&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <asp:textbox runat="server" id="projectNameSearch" type="text" MaxLength="10"/>
                <asp:Button ID="Button1" runat="server" Height="24px" OnClick="TrigSearchProject" style="margin-left: 0px" Text="Search" Width="135px" />
                <p style="width: 643px">
                    Leave Text Box Empty and Search to see all Projects<div style="text-align: center">
                    <asp:GridView ID="projectGridView" AutoGenerateColumns="False" runat="server"  style="left: 311px; top: 799px" Width="545px" 
                         OnRowCancelingEdit="projectGridView_RowCancelingEdit" OnRowEditing="projectGridView_RowEditing" OnRowUpdating="projectGridView_RowUpdating" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ProjectID" ShowHeaderWhenEmpty="True" OnRowDeleting="projectGridView_RowDeleting">
                        <Columns>
                            <asp:TemplateField HeaderText="ProjectID">
                                <EditItemTemplate>
                                    <asp:TextBox ID="projectIDtxt" runat="server" Text='<%# Eval("ProjectID") %>' ReadOnly="True"></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="projectIDtxt" runat="server" ReadOnly="True" Text='<%# Eval("ProjectID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="projectIDlbl" runat="server" Text='<%# Eval("ProjectID") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ProjectName">
                                <EditItemTemplate>
                                    <asp:TextBox ID="ProjectNametxt" runat="server" Text='<%# Eval("ProjectName") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="projectIDtxt" runat="server" ReadOnly="True" Text='<%# Eval("ProjectID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="ProjectNamelbl" runat="server" Text='<%# Eval("ProjectName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="ProjectDescription">
                                <EditItemTemplate>
                                    <asp:TextBox ID="projectDescriptiontxt" runat="server" Text='<%# Eval("ProjectDescription") %>' TextMode="MultiLine"></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="projectIDtxt" runat="server" ReadOnly="True" Text='<%# Eval("ProjectID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="ProjectDescriptionlbl" runat="server" Text='<%# Eval("ProjectDescription") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="LastUpdatedBy">
                                <EditItemTemplate>
                                    <asp:TextBox ID="LastUpdatedBytxt" runat="server" Text='<%# Eval("LastUpdatedBy") %>' ReadOnly="True"></asp:TextBox>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <asp:TextBox ID="projectIDtxt" runat="server" ReadOnly="True" Text='<%# Eval("ProjectID") %>'></asp:TextBox>
                                </FooterTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LastUpdatedBylbl" runat="server" Text='<%# Eval("LastUpdatedBy") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EmptyDataTemplate>
                            <asp:Label ID="Label6" runat="server" Text="No Records Found"></asp:Label>
                        </EmptyDataTemplate>
                        </asp:GridView>
                    <br />
                    <br />

                </div>
                </p>
</asp:Content>

